# Copyright © 2025 Brent Tunnicliff <brent@tunnicliff.dev>

name: Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  package:
    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/common.yml@wip
    strategy:
      matrix:
        platform: ["iOS", "macOS", "tvOS", "watchOS", "visionOS"]
        skip_tests: [true, false]
        exclude:
          - platform: "iOS"
            skip_tests: true
          - platform: "macOS"
            skip_tests: true
          - platform: "tvOS"
            skip_tests: true
          - platform: "watchOS"
            skip_tests: false
          - platform: "visionOS"
            skip_tests: true
    with:
      platform: "${{ matrix.platform }}"
      scheme: "App"
      skip_tests: ${{ matrix.skip_tests }}
